version: "3.7"

services:
  nevergreen:
    image: buildcanariesteam/nevergreen:latest
    ports:
      - 5000:5000
    depends_on:
      - bamboo_cctray_proxy

  bamboo_cctray_proxy:
    image: chadwilson/bamboo_cctray_proxy:latest
    ports:
      - 7001:7001
    volumes:
      - ./config:/app/config

  curl_cctray:
    image: ghcr.io/containeroo/alpine-toolbox:latest
    command: >
      curl --retry 10 --retry-delay 1 --retry-connrefused
      http://bamboo_cctray_proxy:7001/dashboard/cctray.xml
    depends_on:
      - bamboo_cctray_proxy

  curl_nevergreen:
    image: ghcr.io/containeroo/alpine-toolbox:latest
    volumes:
      - ./config:/config
    command: >
      curl --retry 10 --retry-delay 10 --retry-connrefused
      -X POST http://nevergreen:5000/api/projects
      -H 'Content-Type: application/json' -H 'cache-control: no-cache'
      --data-binary '@/config/nevergreen.json'
    depends_on:
      - curl_cctray
      - bamboo_cctray_proxy
      - nevergreen
